### @name GET_TASKS

GET {{host}}/api/tasks HTTP/1.1


### @name GET_TASK_BY_ID

GET {{host}}/api/tasks/783cb33c-7888-4b19-9963-dbcac0760b89 HTTP/1.1


### @name CREATE_TASK

POST {{host}}/api/tasks HTTP/1.1
Content-Type: application/json

{
  "description": "This is a new task created via HTTP request.",
  "title": "Feed my cat"
}


### @name DELETE_TASK

DELETE {{host}}/api/tasks/783cb33c-7888-4b19-9963-dbcac0760b89 HTTP/1.1
